#!/bin/sh

#REMEMBER to set the proper amount of N robots below

PACKAGEuser="nexhom"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch $PACKAGEuser N_nexus.launch N:=3 &        #The N here tells the roslaunch file how many robots to spawn



sleep 10

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  echo $i &

  xterm -e rosrun $PACKAGEuser dataprocessingnode_N.py "$i" &

  xterm -e rosrun $PACKAGEuser hom_enc2_est_v2.py "$i" &

  xterm -e rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2.py "$i" &

  xterm -e rosrun $PACKAGEuser hom_dec2_est_v2.py "$i" &


 done


sleep 10

echo
echo "Press Ctrl-C to terminate"
echo

wait
