#!/bin/sh

#REMEMBER to set the proper amount of N within N_nexus.launch and add the new spawn robots in N_world.launch

PACKAGEuser="nexus_encrypted_control"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch $PACKAGEuser N_nexus.launch N:=3 &



sleep 10

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  echo $i &

  rosrun $PACKAGEuser dataprocessingnode_N.py "$i" &

  rosrun $PACKAGEuser hom_enc2.py "$i" &

  rosrun $PACKAGEuser controller_N_hom_encr_formation.py "$i" &

  rosrun $PACKAGEuser hom_dec2.py "$i" &

  #sleep 20 &


 done

echo
echo "Press Ctrl-C to terminate"
echo

wait