#!/bin/sh

#REMEMBER to set the proper amount of N below in "N:=3" and add the new spawn robots in Spawn_N_agents_gazebo.launch

PACKAGEuser="nexus_encrypted_control"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch gazebo_ros

sleep 2

roslaunch $PACKAGEuser N_nexus.launch N:=3 &



sleep 10

echo
echo "Launching Data Processing Node"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  xterm -e rosrun $PACKAGEuser dataprocessingnode_N_v3.py "$i" &

 done

sleep 2

echo
echo "Launching Encryption Node"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  gnome-terminal -- bash -c "rosrun $PACKAGEuser hom_enc2_est_v3.py "$i"; exec bash" &

 done

sleep 2

echo
echo "Launching Encrypted Controller Node"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  gnome-terminal -- bash -c "rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v3.py "$i"; exec bash" &

 done

sleep 2

echo
echo "Launching decryption Node"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  gnome-terminal -- bash -c "rosrun $PACKAGEuser hom_dec2_est_v3.py "$i"; exec bash" &

 done

echo
echo "Press Ctrl-C to terminate"
echo

wait
