#!/bin/sh

#REMEMBER to set the proper amount of N within N_nexus.launch and add the new spawn robots in N_world.launch

PACKAGEuser="nexhom"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch $PACKAGEuser N_nexus.launch N:=1 &


sleep 10

for i in 1    #add new values here depending on N amount of robots

 do 

  echo $i &

  xterm -e rosrun $PACKAGEuser dataprocessingnode_N.py "$i" &

  xterm -e  rosrun $PACKAGEuser hom_enc2.py "$i" &

  xterm -e  rosrun $PACKAGEuser controller_1_hom_encr2.py "$i" &

  xterm -e  rosrun $PACKAGEuser hom_dec2.py "$i" 


 done

echo
echo "Press Ctrl-C to terminate"
echo

wait