#!/bin/bash

#REMEMBER to set the proper amount of N robots below

PACKAGEuser="nexhom"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch $PACKAGEuser N_nexus.launch N:=3 &        #The N here tells the roslaunch file how many robots to spawn

last_pid_gaz=$!

sleep 10

for j in $(seq 1 50) #execute controllers over and over
	do
	 
	#rosrun $PACKAGEuser listener_data.py "$j" &

	#listener_pid=$!
	
	rosrun $PACKAGEuser dataprocessingnode_N.py "1" &

	last_pid_data1=$!

	rosrun $PACKAGEuser dataprocessingnode_N.py "3" &

	last_pid_data3=$!

	rosrun $PACKAGEuser dataprocessingnode_N.py "2" &

	last_pid_data2=$!

	sleep 1



	rosrun $PACKAGEuser hom_enc2_est_v2_str.py "1" &

	last_pid_enc1=$!

	rosrun $PACKAGEuser hom_enc2_est_v2_str.py "2" &

	last_pid_enc2=$!

	rosrun $PACKAGEuser hom_enc2_est_v2_str.py "3" &

	last_pid_enc3=$!

	sleep 1

	rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2_str.py "1" &

	last_pid_cont1=$!

	rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2_str.py "2" &

	last_pid_cont2=$!

	rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2_str.py "3" &

	last_pid_cont3=$!

	sleep 2

	rosrun $PACKAGEuser hom_dec2_est_v2_str.py "3" &

	last_pid_dec3=$!

	rosrun $PACKAGEuser hom_dec2_est_v2_str.py "2" &

	last_pid_dec2=$!

	rosrun $PACKAGEuser hom_dec2_est_v2_str.py "1" &

	last_pid_dec1=$!

	
	sleep 25
	
	kill -INT $last_pid_dec1
	kill -INT $last_pid_dec2
	kill -INT $last_pid_dec3

	sleep 1

	kill -INT $last_pid_cont1
	kill -INT $last_pid_enc1
	kill -INT $last_pid_cont2
	kill -INT $last_pid_enc2
	kill -INT $last_pid_cont3
	kill -INT $last_pid_enc3

	kill -INT $last_pid_data1
	kill -INT $last_pid_data2
	kill -INT $last_pid_data3  #kill all controllers and dataprocessors to restart them

	kill -INT $listener_pid

	rostopic pub -1  /n_1/cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.0, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}' &
	rostopic pub -1  /n_2/cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.0, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}' &
	rostopic pub -1  /n_3/cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.0, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}' &
	
	sleep 1

	#rosservice call /gazebo/reset_world "{}"   #resets simulation in Gazebo
	rosservice call /gazebo/reset_simulation "{}"

	echo "Round $j"

	sleep 2

	done
wait
