#!/bin/sh

#REMEMBER to set the proper amount of N robots below

PACKAGEuser="nexhom"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

roslaunch $PACKAGEuser N_nexus.launch N:=3 &        #The N here tells the roslaunch file how many robots to spawn



sleep 10

echo
echo "Launching Data Processing Node"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  #echo $i &

  xterm -e rosrun $PACKAGEuser dataprocessingnode_N.py "$i" &

done

sleep 4

echo
echo "Launching Encryption"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  #echo $i &

  xterm -e rosrun $PACKAGEuser hom_enc2_est_v2_str.py "$i" &

  #gnome-terminal -- bash -c "rosrun $PACKAGEuser hom_enc2_est_v2_str.py "$i"; exec bash" &
  
  sleep 0.5

done
  
sleep 4

echo
echo "Launching Encrypted Controller"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  #echo $i &

  xterm -e rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2_str.py "$i" &

  #gnome-terminal -- bash -c "rosrun $PACKAGEuser controller_N_hom_encr_formation_est_v2_str.py "$i"; exec bash" &

  echo

  sleep 0.5

done

sleep 4

echo
echo "Launching Decryption"
echo

for i in 1 2 3   #add new values here depending on N amount of robots

 do 

  #echo $i &

  xterm -e rosrun $PACKAGEuser hom_dec2_est_v2_str.py "$i" &

  #gnome-terminal -- bash -c "rosrun $PACKAGEuser hom_dec2_est_v2_str.py "$i"; exec bash" &

  echo

done


sleep 4

#echo "Press 'r' to reset gazebo simulation"
#count=0
#while : ; do
#read -n k <&1
#  if [[ $k = r ]] ; then
#    echo
#    echo "Resetting Simulation"
#    rosservice call /gazebo/reset_simulation "{}"
#  else
#    ((count=$count+1))
#  fi
#done

echo
echo "Press Ctrl-C to terminate"
echo

wait

#in something goes wrong and ros didn't close then use "killall -9 rosmaster" and "killall -9 roscore"

#to reset gazebo simulation without having to start and close use : " rosservice call /gazebo/reset_simulation "{}" "
