#!/bin/bash

#REMEMBER to set the proper amount of N robots below

PACKAGEuser="nexus_encrypted_control"       #CHANGE THIS VARIABLE TO NAME OF PACKAGE

echo

echo NOW EXECUTING SCRIPTS FROM THE PACKAGE: $PACKAGEuser

echo

#roslaunch $PACKAGEuser N_nexus.launch N:=3 &        #The N here tells the roslaunch file how many robots to spawn

set --

echo
echo "Launching Data Processing Node"
echo


xterm -e python &

sleep 1

set -- "$@" "$!"

xterm -e python &

last_pid3=$! &

xterm -e python &

last_pid4=$! &

echo "$1" &

kill -KILL "$1" &


#echo "Press 'r' to reset gazebo simulation"
#count=0
#while : ; do
#read -n k <&1
#  if [[ $k = r ]] ; then
#    echo
#    echo "Resetting Simulation"
#    rosservice call /gazebo/reset_simulation "{}"
#  else
#    ((count=$count+1))
#  fi
#done

echo
echo "Press Ctrl-C to terminate"
echo

wait

#in something goes wrong and ros didn't close then use "killall -9 rosmaster" and "killall -9 roscore"

#to reset gazebo simulation without having to start and close use : " rosservice call /gazebo/reset_simulation "{}" "
